
services:
  app:
    build: ./app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DB_PASSWORD: $DB_PASSWORD
  db:
    build: ./mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'web'
      # Password for root access
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql: