@Library('pipeline-library') _
pipeline{
    agent{
        label "ubuntu"
    }

    stages{
        stage("Print webhook parameters"){
            steps{
                script {
                  functions.prepareEnv(WebhookJson)
                  
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
